import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MyHeader } from '@/components/custom/MyHeader';
import AllProvider from '@/redux/AllProvider';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout(props: Readonly<RootLayoutProps>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MyHeader>
          <Link
            slot='title'
            href={'about'}>
            Flowbite
          </Link>
          <Link
            slot='actions'
            href={'about'}>
            About
          </Link>
          <Link
            slot='actions'
            href={'category'}>
            Category
          </Link>
        </MyHeader>
        <AllProvider>{props.children}</AllProvider>
      </body>
    </html>
  );
}
